
name: mobile_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pie_chart: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf